# Generated by Django 4.1.4 on 2022-12-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newtask',
        ),
    ]
